//DELETE http://localhost:3001/api/persons/3
// Content-Type: application/json

//GET http://localhost:3001/api/persons


POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Dan Abramov",
    "number": "39-23-6423122"
}